// ============================================================
// VOLO SST V9 — DATA.js
// Fichier de données centralisé (partagé par index, dashboard, pointage)
// Généré le 2026-02-27
// ============================================================

const PERSONNEL = [
  {id:"SAUV-AG-075",volo:"V0075",name:"Alexandre Gendreau",role:"CHEF D'EQUIPE",type:"SAUVETEUR",region:"ESTRIE",ville:"Austin"},
  {id:"SAUV-MB-180",volo:"V0180",name:"Maxime Boisvert",role:"CHEF D'EQUIPE",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-YB-077",volo:"V0077",name:"Yann-Alexandre Belley",role:"CHEF D'EQUIPE",type:"SAUVETEUR",region:"ESTRIE",ville:"Austin"},
  {id:"SAUV-AD-076",volo:"V0076",name:"Antoine Dépôt",role:"COORDONNATEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-CS-178",volo:"V0178",name:"Carl St-Pierre",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Dixville"},
  {id:"SAUV-CL-115",volo:"V0115",name:"Cédric Lapointe-Stewart",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-DB-172",volo:"V0172",name:"Denis Bélanger",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Shefford"},
  {id:"SAUV-FM-182",volo:"V0182",name:"Frédéric Massicotte",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-GM-206",volo:"V0206",name:"Gérard Morin",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Dudswell"},
  {id:"SAUV-JM-205",volo:"V0205",name:"Jonathan Milone",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-ML-113",volo:"V0113",name:"Mathieu Lapalme",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Westbury"},
  {id:"SAUV-ML-339",volo:"V0339",name:"Maxime Lavigne",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SAUV-OL-114",volo:"V0114",name:"Olivier Lessard",role:"SAUVETEUR",type:"SAUVETEUR",region:"ESTRIE",ville:"Sherbooke"},
  {id:"SURV-AA-364",volo:"V0364",name:"Alexis Allain",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-AM-359",volo:"V0359",name:"Alice Milot",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Lac-Supérieur"},
  {id:"SURV-AB-272",volo:"V0272",name:"André Boucher",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-AR-281",volo:"V0281",name:"André Raymond",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-AG-348",volo:"V0348",name:"Antoine Gagnon",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-AG-314",volo:"V0314",name:"Antoine Giguère",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Magog"},
  {id:"SURV-BC-274",volo:"V0274",name:"Benoit Courtemanche",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-BB-362",volo:"V0362",name:"Berbard Boutin",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-CL-363",volo:"V0363",name:"Charles Lebel Désorcy",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-CP-111",volo:"V0111",name:"Charles Poisson",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Blainville"},
  {id:"SURV-CB-368",volo:"V0368",name:"Claude Boily",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Coaticook"},
  {id:"SURV-DD-350",volo:"V0350",name:"Daniel Durand",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-DT-361",volo:"V0361",name:"Danielle Thibeault",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Shefford"},
  {id:"SURV-DL-320",volo:"V0320",name:"David Laroche",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-DG-319",volo:"V0319",name:"Dominic Gauthier",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Magog"},
  {id:"SURV-EP-263",volo:"V0263",name:"Esther Payeur",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-EH-286",volo:"V0286",name:"Etienne Houle Grimard",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-FJ-360",volo:"V0360",name:"Fernand Jacob",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Shefford"},
  {id:"SURV-FL-342",volo:"V0342",name:"Frédéric Lalonde",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Cookshire-Eaton"},
  {id:"SURV-GP-347",volo:"V0347",name:"Gabriel Paris",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-GF-302",volo:"V0302",name:"Gabrielle Fontaine",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Ascot Corner"},
  {id:"SURV-GG-122",volo:"V0122",name:"Gilles Gaudette",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-GB-371",volo:"V0371",name:"Guillaume Boisvert",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Wotton"},
  {id:"SURV-GM-207",volo:"V0207",name:"Guillaume Morin",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Dudswell"},
  {id:"SURV-JL-288",volo:"V0288",name:"Jacques Lawrence",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Val des Sources"},
  {id:"SURV-JP-335",volo:"V0335",name:"Jaysen Poulin",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Magog"},
  {id:"SURV-JP-124",volo:"V0124",name:"Jean Parr",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-JT-217",volo:"V0217",name:"Jean Turgeon",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-JL-282",volo:"V0282",name:"Jean-François Labbé",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"SHERBROOKE"},
  {id:"SURV-JP-223",volo:"V0223",name:"Jean-Marc Pagé",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Magog"},
  {id:"SURV-JB-108",volo:"V0108",name:"Jean-Nicolas Bouthot",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Coaticook"},
  {id:"SURV-JB-343",volo:"V0343",name:"Jean-Tomas Blais",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-JT-220",volo:"V0220",name:"Jessy Trudeau",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-JM-137",volo:"V0137",name:"Jovo Maric",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-LA-082",volo:"V0082",name:"Laurent Allain",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-LA-325",volo:"V0325",name:"Lee-Ann Avon-Monast",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Cowansville"},
  {id:"SURV-LB-189",volo:"V0189",name:"Lina Boutin",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-LA-079",volo:"V0079",name:"Louise Allain",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-LB-373",volo:"V0373",name:"Loïc Bélange",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"St-Norbert d'Artabska"},
  {id:"SURV-MA-081",volo:"V0081",name:"Madeleine Allain",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-MB-187",volo:"V0187",name:"Marc Bergeron",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-MN-270",volo:"V0270",name:"Marcel Nadeau",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Compton"},
  {id:"SURV-MA-135",volo:"V0135",name:"Marianne Allain",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Cookshire-Eaton"},
  {id:"SURV-MG-192",volo:"V0192",name:"Mario Guillemette",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-MG-292",volo:"V0292",name:"Martin Guillemette",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Stoke"},
  {id:"SURV-MO-208",volo:"V0208",name:"Mathieu Ouellette",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Cookshire-Eaton"},
  {id:"SURV-MS-290",volo:"V0290",name:"Michaël St-Jean-Lévêque",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"SHERBROOKE"},
  {id:"SURV-MC-225",volo:"V0225",name:"Michel Cloutier",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-ML-365",volo:"V0365",name:"Michel Lemieux",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-MT-100",volo:"V0100",name:"Michel Trudeau",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-ML-384",volo:"V0384",name:"Michelle Leroux",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"East Augus"},
  {id:"SURV-NL-271",volo:"V0271",name:"Nathalie Labrecque",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-NK-326",volo:"V0326",name:"Ndeye Fatou Kamara",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-OG-283",volo:"V0283",name:"Olivier Grenier-Moya",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"SAINT-DENIS-DE-BROMPTON"},
  {id:"SURV-OS-333",volo:"V0333",name:"Olivier Sheehan",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-PB-289",volo:"V0289",name:"Patrick Beaulne",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"SHERBROOKE"},
  {id:"SURV-PH-193",volo:"V0193",name:"Pierre Héroux",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-RA-299",volo:"V0299",name:"Raymond Armand",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"WOTTON"},
  {id:"SURV-RS-280",volo:"V0280",name:"Raymond St-Cyr",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Compton"},
  {id:"SURV-RH-112",volo:"V0112",name:"Robert Hamel",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-RL-200",volo:"V0200",name:"Rock Lussier",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Windsor"},
  {id:"SURV-RB-353",volo:"V0353",name:"Rodérick Brochu",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-RM-204",volo:"V0204",name:"Roger Mathieu",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Saint-Herménégilde"},
  {id:"SURV-SL-197",volo:"V0197",name:"Steve Lessard",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Sherbrooke"},
  {id:"SURV-SB-086",volo:"V0086",name:"Sébastien Bernard",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Waterloo"},
  {id:"SURV-TL-337",volo:"V0337",name:"Thomas Lecorne",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Granby"},
  {id:"SURV-VG-080",volo:"V0080",name:"Véronique Gendreau",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"Cookshire-Eaton"},
  {id:"SURV-YD-101",volo:"V0101",name:"Yves Denis",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"East-Angus"},
  {id:"SURV-ZG-331",volo:"V0331",name:"Zachary Gelé",role:"SURVEILLANT",type:"SURVEILLANT",region:"ESTRIE",ville:"East-Angus"},
  {id:"SAUV-PM-089",volo:"V0089",name:"Phillippe Monnier",role:"CHEF D'EQUIPE",type:"SAUVETEUR",region:"CAPITALE-NATIONALE",ville:"Saint-Augustin de Desmaures"},
  {id:"SAUV-DF-088",volo:"V0088",name:"Daniel Faucher",role:"SAUVETEUR",type:"SAUVETEUR",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SAUV-TD-157",volo:"V0157",name:"Tommy Drolet",role:"SAUVETEUR",type:"SAUVETEUR",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SAUV-YG-327",volo:"V0327",name:"Yani Goulet",role:"SAUVETEUR",type:"SAUVETEUR",region:"CAPITALE-NATIONALE",ville:"Stoneham-et-Tewkesbury"},
  {id:"SURV-AR-128",volo:"V0128",name:"Amy Racette",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Saint-Augustin-de Desmaures"},
  {id:"SURV-AD-355",volo:"V0355",name:"Anthony Dallaire",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-CF-295",volo:"V0295",name:"Constantin Fournier",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"VAL-RACINE"},
  {id:"SURV-GF-238",volo:"V0238",name:"Gabrielle Ferland",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-JC-258",volo:"V0258",name:"Jasmin Côté",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-JP-249",volo:"V0249",name:"Jean-Philippe Paquet",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Scott"},
  {id:"SURV-JF-251",volo:"V0251",name:"Jonathan Fournier",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-ML-097",volo:"V0097",name:"Marc-André Lebrun",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-MC-250",volo:"V0250",name:"Maxime Chicoine",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"L'Ancienne-Lorette"},
  {id:"SURV-MC-309",volo:"V0309",name:"Mikael Cusson",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-MC-307",volo:"V0307",name:"Médérick Champoux",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-NV-306",volo:"V0306",name:"Nathan Veilleux",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-OM-305",volo:"V0305",name:"Olivier Messier",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-RP-328",volo:"V0328",name:"Rodrigue Paquette",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Portneuf"},
  {id:"SURV-SM-308",volo:"V0308",name:"Sarah-Claude Miranda",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-SB-329",volo:"V0329",name:"Simon-Pier Bégin",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Lévis"},
  {id:"SURV-ZJ-310",volo:"V0310",name:"Zachary Jalbert",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SURV-ÉD-354",volo:"V0354",name:"Émerik Drolet",role:"SURVEILLANT",type:"SURVEILLANT",region:"CAPITALE-NATIONALE",ville:"Québec"},
  {id:"SAUV-BG-105",volo:"V0105",name:"Benjamin Grenier",role:"SAUVETEUR",type:"SAUVETEUR",region:"MAURICIE",ville:"Notre-Dame du Mont Carmel"},
  {id:"SAUV-DA-116",volo:"V0116",name:"Danny Alie",role:"SAUVETEUR",type:"SAUVETEUR",region:"MAURICIE",ville:"Drummondville"},
  {id:"SAUV-PP-210",volo:"V0210",name:"Pier-Paul Pelletier-Gamache",role:"SAUVETEUR",type:"SAUVETEUR",region:"MAURICIE",ville:"Drummondville"},
  {id:"SAUV-TR-121",volo:"V0121",name:"Tommy Raymond",role:"SAUVETEUR",type:"SAUVETEUR",region:"MAURICIE",ville:"Trois-Rivières"},
  {id:"SAUV-WG-313",volo:"V0313",name:"William Girard",role:"SAUVETEUR",type:"SAUVETEUR",region:"MAURICIE",ville:"Drummondville"},
  {id:"SURV-AG-279",volo:"V0279",name:"Alain Gélinas",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Trois-Rivières"},
  {id:"SURV-AG-276",volo:"V0276",name:"André Gignac",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Trois-Rivières"},
  {id:"SURV-CB-119",volo:"V0119",name:"Camille Bernard",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Trois-Rivières"},
  {id:"SURV-CG-275",volo:"V0275",name:"Christian Gignac",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"TROIS-RIVIÈRES"},
  {id:"SURV-DF-366",volo:"V0366",name:"Denis Fréchette",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Drummondville"},
  {id:"SURV-DV-324",volo:"V0324",name:"Dylan Vaudreuil",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Warwick"},
  {id:"SURV-FG-277",volo:"V0277",name:"Frédéric Germain",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Trois-Rivières"},
  {id:"SURV-GM-287",volo:"V0287",name:"Gilbert Martyial",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Trois-Rivière"},
  {id:"SURV-HF-294",volo:"V0294",name:"Heavenly Fournier",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"NOTRE-DAME-DU-MONT-CARMEL"},
  {id:"SURV-IB-293",volo:"V0293",name:"Ian Blanchette Fortin",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Notre-Dame-du-Mont-Carmel"},
  {id:"SURV-NR-375",volo:"V0375",name:"Nicole Raymond",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Victoriaville"},
  {id:"SURV-PL-247",volo:"V0247",name:"Pierre-Olivier Lacoursiere",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Shawinigan"},
  {id:"SURV-ÉB-098",volo:"V0098",name:"Éric Boucher",role:"SURVEILLANT",type:"SURVEILLANT",region:"MAURICIE",ville:"Shawinigan"},
  {id:"SAUV-CV-181",volo:"V0181",name:"Charles Vigeant",role:"SAUVETEUR",type:"SAUVETEUR",region:"LANAUDIÈRE",ville:"Terrebonne"},
  {id:"SAUV-HD-179",volo:"V0179",name:"Hugues Dépatie",role:"SAUVETEUR",type:"SAUVETEUR",region:"LANAUDIÈRE",ville:"Saint-Sauveur"},
  {id:"SURV-AR-376",volo:"V0376",name:"Adrien Raymond",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Lac-Mégantic"},
  {id:"SURV-AF-118",volo:"V0118",name:"Alex Frigon",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Terrebonne"},
  {id:"SURV-AS-318",volo:"V0318",name:"Alexandre Sammut",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Terrebonne"},
  {id:"SURV-CM-203",volo:"V0203",name:"Chelsey-Todd Martin",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Repentigny"},
  {id:"SURV-CK-296",volo:"V0296",name:"Corentin Korbi",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"MASCOUCHE"},
  {id:"SURV-GB-311",volo:"V0311",name:"Gabriel Boisclair",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Mascouche"},
  {id:"SURV-MO-120",volo:"V0120",name:"Mohamed-Yazid Oussadi",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"Terrebonne"},
  {id:"SURV-NV-224",volo:"V0224",name:"Noémie Villeneuve",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"St-Lin-Laurentides"},
  {id:"SURV-RH-297",volo:"V0297",name:"Racim Hassaim",role:"SURVEILLANT",type:"SURVEILLANT",region:"LANAUDIÈRE",ville:"MASCOUCHE"},
  {id:"SAUV-AP-183",volo:"V0183",name:"Alexandre Pelaez-Bouchard",role:"SAUVETEUR",type:"SAUVETEUR",region:"MONTRÉAL",ville:"Montréal"},
  {id:"SAUV-NF-209",volo:"V0209",name:"Nikola Forté Millones",role:"SAUVETEUR",type:"SAUVETEUR",region:"MONTRÉAL",ville:"Montréal"},
  {id:"SURV-DL-298",volo:"V0298",name:"Derrick Le",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"SAINT-LÉONARD"},
  {id:"SURV-IB-372",volo:"V0372",name:"Ismaël Barry",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"Ste-Martine"},
  {id:"SURV-MB-094",volo:"V0094",name:"Mohamed Belhani",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"Montréal"},
  {id:"SURV-SM-106",volo:"V0106",name:"Saïd Abderaouf Mokhtari",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"Montréal"},
  {id:"SURV-YB-104",volo:"V0104",name:"Youcef Bourelam",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"Montréal,"},
  {id:"SURV-ZB-273",volo:"V0273",name:"Zoubir Abdallah Benyamina",role:"SURVEILLANT",type:"SURVEILLANT",region:"MONTRÉAL",ville:"SAINT-LÉONARD"},
  {id:"SURV-AA-278",volo:"V0278",name:"Alexandre Adams",role:"SURVEILLANT",type:"SURVEILLANT",region:"OUTAOUAIS",ville:"Gatineau"},
  {id:"SURV-CB-229",volo:"V0229",name:"Charles Bélanger",role:"SURVEILLANT",type:"SURVEILLANT",region:"OUTAOUAIS",ville:"Saint-Sixte"},
  {id:"SURV-FB-228",volo:"V0228",name:"Félix Bélanger",role:"SURVEILLANT",type:"SURVEILLANT",region:"OUTAOUAIS",ville:"Saint Sixte"},
  {id:"SURV-JS-095",volo:"V0095",name:"Julien Sasseville",role:"SURVEILLANT",type:"SURVEILLANT",region:"OUTAOUAIS",ville:"Saint-Sixte"},
  {id:"SURV-ND-358",volo:"V0358",name:"Nathalie Daneau",role:"SURVEILLANT",type:"SURVEILLANT",region:"OUTAOUAIS",ville:"Saint-Sixte"},
  {id:"SAUV-JM-357",volo:"V0357",name:"Jean-Nicolas Maisonneuve",role:"CHEF D'EQUIPE",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-AD-389",volo:"V0389",name:"Alex Duguay",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-DR-388",volo:"V0388",name:"David Ross",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-JC-379",volo:"V0379",name:"Jacob Corbin",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-MB-385",volo:"V0385",name:"Maxim Béland",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-PG-370",volo:"V0370",name:"Patrice Garon",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-RC-381",volo:"V0381",name:"Rock Caissy",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SAUV-YC-387",volo:"V0387",name:"Yves Canuel",role:"SAUVETEUR",type:"SAUVETEUR",region:"BAS-ST-LAURENT",ville:"Rimouski"},
  {id:"SURV-CR-367",volo:"V0367",name:"Clementyne Raymond",role:"SURVEILLANT",type:"SURVEILLANT",region:"NON-CLASSE",ville:""},
  {id:"SURV-SP-338",volo:"V0338",name:"Samuel Provost",role:"SURVEILLANT",type:"SURVEILLANT",region:"NON-CLASSE",ville:""}
];
const SAUVETEURS = PERSONNEL;

let ITEMS = [
  {id:"ITEM-SAC-001",name:"Sac Paramédic A",cat:"Paramédic",icon:"🩺",sceau:true},
  {id:"ITEM-SAC-002",name:"Sac Paramédic B",cat:"Paramédic",icon:"🩺",sceau:true},
  {id:"ITEM-SAC-003",name:"Sac Paramédic C",cat:"Paramédic",icon:"🩺",sceau:true},
  {id:"ITEM-SAC-004",name:"Sac Paramédic D",cat:"Paramédic",icon:"🩺",sceau:true},
  {id:"ITEM-HAR-001",name:"Harnais #1",cat:"Corde",icon:"🪢"},{id:"ITEM-HAR-002",name:"Harnais #2",cat:"Corde",icon:"🪢"},
  {id:"ITEM-HAR-003",name:"Harnais #3",cat:"Corde",icon:"🪢"},{id:"ITEM-HAR-004",name:"Harnais #4",cat:"Corde",icon:"🪢"},
  {id:"ITEM-HAR-005",name:"Harnais #5",cat:"Corde",icon:"🪢"},{id:"ITEM-HAR-006",name:"Harnais #6",cat:"Corde",icon:"🪢"},
  {id:"ITEM-DET-001",name:"Détecteur Gaz #1",cat:"Détection",icon:"🔬"},{id:"ITEM-DET-002",name:"Détecteur Gaz #2",cat:"Détection",icon:"🔬"},
  {id:"ITEM-DET-003",name:"Détecteur Gaz #3",cat:"Détection",icon:"🔬"},
  {id:"ITEM-GRI-001",name:"Grillon #1",cat:"Corde",icon:"🔗"},{id:"ITEM-GRI-002",name:"Grillon #2",cat:"Corde",icon:"🔗"},
  {id:"ITEM-GRI-003",name:"Grillon #3",cat:"Corde",icon:"🔗"},
  {id:"ITEM-COR-001",name:"Corde #1",cat:"Corde",icon:"🧶"},{id:"ITEM-COR-002",name:"Corde #2",cat:"Corde",icon:"🧶"},
  {id:"ITEM-SKD-001",name:"Sked Pack #1",cat:"Évacuation",icon:"🛷"},{id:"ITEM-SKD-002",name:"Sked Pack #2",cat:"Évacuation",icon:"🛷"},
  {id:"ITEM-BAS-001",name:"Basket #1",cat:"Évacuation",icon:"🧺"},{id:"ITEM-BAS-002",name:"Basket #2",cat:"Évacuation",icon:"🧺"},
  {id:"ITEM-EVA-001",name:"Kit Évacuation #1",cat:"Évacuation",icon:"🚑"},{id:"ITEM-EVA-002",name:"Kit Évacuation #2",cat:"Évacuation",icon:"🚑"},
  {id:"ITEM-INT-001",name:"Sac Intervention #1",cat:"Intervention",icon:"🎒"},{id:"ITEM-INT-002",name:"Sac Intervention #2",cat:"Intervention",icon:"🎒"},
];

// Catégories dérivées des items (pour filtre UI)
const ITEM_CATEGORIES = [...new Set(ITEMS.map(i => i.cat))];

let DEPOTS = [
  {id:"DEP-KRUGER",name:"Kruger Brompton",region:"ESTRIE"},
  {id:"DEP-MAGOG",name:"Magog — Chantier Hydro",region:"ESTRIE"},
  {id:"DEP-QC",name:"Québec — Base",region:"CAPITALE-NATIONALE"},
  {id:"DEP-3R",name:"Trois-Rivières — Base",region:"MAURICIE"},
  {id:"DEP-RIM",name:"Rimouski — Base",region:"BAS-ST-LAURENT"},
];

let DESTINATIONS = [
  {id:"DEST-SHERB-K",name:"Sherbrooke — Usine Kruger",region:"ESTRIE"},
  {id:"DEST-MAGOG",name:"Magog — Chantier Hydro",region:"ESTRIE"},
  {id:"DEST-QC-VAL",name:"Québec — Raffinerie Valero",region:"CAPITALE-NATIONALE"},
  {id:"DEST-QC-PORT",name:"Québec — Port",region:"CAPITALE-NATIONALE"},
  {id:"DEST-LEVIS",name:"Lévis — Chantier Davie",region:"CAPITALE-NATIONALE"},
  {id:"DEST-3R-HQC",name:"Trois-Rivières — Hydro-QC",region:"MAURICIE"},
  {id:"DEST-DRUM",name:"Drummondville — Usine",region:"MAURICIE"},
  {id:"DEST-MTL-PONT",name:"Montréal — Chantier Pont",region:"MONTRÉAL"},
  {id:"DEST-RIM-CASC",name:"Rimouski — Papeterie Cascades",region:"BAS-ST-LAURENT"},
];

// V8 – Véhicules simplifiés: Pick-Up + Trailer seulement
let REMORQUES = [
  {id:"REM-PU1",name:"Pick-Up 1"},
  {id:"REM-PU2",name:"Pick-Up 2"},
  {id:"REM-TR1",name:"Trailer 1"},
  {id:"REM-TR2",name:"Trailer 2"}
];

const CERTS_LIST = [
  {id:'espace-clos',name:'Espace clos',dur:12,icon:'🕳️'},
  {id:'hauteur',name:'Travail en hauteur',dur:12,icon:'🧗'},
  {id:'rcp',name:'Premiers soins / RCR',dur:36,icon:'❤️'},
  {id:'simdut',name:'SIMDUT 2015',dur:36,icon:'☣️'},
  {id:'cadenassage',name:'Cadenassage / LOTO',dur:12,icon:'🔒'},
  {id:'protection-resp',name:'Protection respiratoire',dur:24,icon:'😷'},
  {id:'chariot',name:'Chariot élévateur',dur:36,icon:'🏗️'},
  {id:'nacelle',name:'Nacelle / plateforme',dur:36,icon:'⬆️'},
  {id:'domtar',name:'Formation DOMTAR',dur:12,icon:'🏭'},
  {id:'kruger',name:'Formation KRUGER',dur:12,icon:'🏭'}
];

const BAREMES = {
  SAUVETEUR: { km_rate:0.68, perdiem_standard:200, perdiem_local:0, urgence_rate:64, urgence_perdiem:85 },
  SURVEILLANT: { km_rate:0.63, perdiem_standard:150, perdiem_local:0, urgence_rate:0, urgence_perdiem:0 }
};
